kind: "Deployment"
metadata:
  annotations:
    fabric8.io/target-platform: "kubernetes"
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-devops/fabric8-docker-registry/src/main/fabric8/icon.png"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "registry:2"
        imagePullPolicy: "IfNotPresent"
        name: "fabric8-docker-registry"
        ports:
        - containerPort: 5000
          name: "http"
        volumeMounts:
        - mountPath: /var/lib/registry
          name: fabric8-docker-registry-storage
          readOnly: false
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      volumes:
      - name: "fabric8-docker-registry-storage"
        persistentVolumeClaim:
          claimName: fabric8-docker-registry-storage
